//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EncuestasUPCEntities : DbContext
    {
        public EncuestasUPCEntities()
            : base("name=EncuestasUPCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Subtipo> Subtipoes { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<DocumentosDigitale> DocumentosDigitales { get; set; }
        public virtual DbSet<Encuesta> Encuestas { get; set; }
        public virtual DbSet<Grupo> Grupoes { get; set; }
        public virtual DbSet<Indicadore> Indicadores { get; set; }
        public virtual DbSet<Opcione> Opciones { get; set; }
        public virtual DbSet<Pregunta> Preguntas { get; set; }
        public virtual DbSet<PreguntasXEncuesta> PreguntasXEncuestas { get; set; }
        public virtual DbSet<Respuesta> Respuestas { get; set; }
        public virtual DbSet<RespuestasXPreguntasXEncuesta> RespuestasXPreguntasXEncuestas { get; set; }
        public virtual DbSet<TipoDocumentoDigital> TipoDocumentoDigitals { get; set; }
        public virtual DbSet<Tipos> Tipos { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
