//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Encuesta()
        {
            this.PreguntasXEncuestas = new HashSet<PreguntasXEncuesta>();
        }
    
        public int id { get; set; }
        public int GrupoId { get; set; }
        public Nullable<int> IndicadorId { get; set; }
        public int DocumentosDigId { get; set; }
        public int SubtipoId { get; set; }
    
        public virtual DocumentosDigitale DocumentosDigitale { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Indicadore Indicadore { get; set; }
        public virtual Subtipo Subtipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreguntasXEncuesta> PreguntasXEncuestas { get; set; }
    }
}
