//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntasXEncuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreguntasXEncuesta()
        {
            this.RespuestasXPreguntasXEncuestas = new HashSet<RespuestasXPreguntasXEncuesta>();
        }
    
        public int id { get; set; }
        public int EncuestaId { get; set; }
        public int PreguntasId { get; set; }
    
        public virtual Encuesta Encuesta { get; set; }
        public virtual Pregunta Pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestasXPreguntasXEncuesta> RespuestasXPreguntasXEncuestas { get; set; }
    }
}
